cart/urls.py
from django.urls import path
from .views import *


app_name = "cart"

urlpatterns = [
    path("", cart_details, name="cart_details"),
    path("add/<int:product_id>", add_to_cart, name="cart_add"),
    path("remove/<int:product_id>", remove_from_cart, name="cart_remove"),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = "orders"

urlpatterns = [
    path("create/", create_order, name="create_order")
]

cart/forms.py
from django import forms
from django.conf import settings


PRODUCTS_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, settings.MAX_CART_ITEMS + 1)]

# (1, "1")

class CartAddForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCTS_QUANTITY_CHOICES,
        coerce=int
    )
    override_quantity = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Product
from .cart import Cart
from .forms import CartAddForm

# Create your views here.

def add_to_cart(request, product_id):
    cart = Cart(request)
    if request.method == "POST":
        cart_form = CartAddForm(request.POST)
        product = get_object_or_404(Product, pk=product_id)
        if cart_form.is_valid():
            cart.add_item(
                product,
                quantity=cart_form.cleaned_data["quantity"],
                override_quantity=cart_form.cleaned_data["override_quantity"]
            )
    return redirect('cart:cart_details')


def cart_details(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddForm(initial={
            "quantity": item["quantity"],
            "override_quantity": True
        })
    return render(request, "cart_details.html", context={"cart": cart})


def remove_from_cart(request, product_id):
    cart = Cart(request)
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        cart.remove_item(product)
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

cart/templates/cart_details.html
{% extends 'base.html' %}

{% block content %}
    <section class="w-75 mb-4 ms-auto me-auto mt-4">
        <div class="border rounded-3">
            <section class="px-3 py-5" style="background-color: #CEC6F5;">
                <div class="row d-flex justify-content-center">
                    <div class="col-xl-11">
                        <div class="row">
                            <div class="col p-2">
                                <div class="d-flex mb-0 justify-content-between align-items-center mb-4">
                                    <h3 class="fw-normal mb-0 text-black">Shopping cart</h3>
                                </div>
                            </div>
                        </div>
                          <div class="col text-end p-2">
                              {% with total_items=cart|length %}
                                {% if total_items > 0 %}
                                    <h3>
                                        Your cart: {{ total_items }} item{{total_items|pluralize}}, $ {{ cart.get_total_price }}
                                    </h3>
                                {% endif %}
                              {% endwith %}
                          </div>
                        {% if not cart %}
                            <div class="card">
                                <div class="card_body p-4 text-center">
                                    <h3>Your cart is empty</h3>
                                </div>
                            </div>
                        {% else %}
                            {% for item in cart %}
                            {% with product=item.product %}
                            <div class="card rounded-3 mb-4">
                                <div class="card-body p-4">
                                    <div class="row d-flex justify-content-between align-items-center">
                                        <div class="col-md-2 col-lg-2 col-xl-2">
                                            <img src="{{ product.pic.url }}" class="img-fluid rounded-3" alt="Image">
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-3">
                                            <p class="lead fw-normal mb-2">{{ product.name }}</p>
                                            <p><span class="text-muted">Category: {{ product.category.name }}</span></p>
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                <div class="d-flex gap-3">
                                                    {% csrf_token %}
                                                    {{ item.update_quantity_form.quantity }}
                                                    {{ item.update_quantity_form.override_quantity }}
                                                    <button class="btn btn-primary" type="submit">Update</button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="col-md-1 col-lg-1 col-xl-1 offset-lg-1">
                                            <h5 class="mb-0">$ {{ item.total_price }}</h5>
                                        </div>
                                        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                                {% csrf_token %}
                                                <button class="btn btn-danger" type="submit">X</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endwith %}
                            {% endfor %}
                    <div class="card">
                        <div class="row p-4">
                            <div class="col p-2">
                                <button class="btn btn-primary" onclick="window.location.href='{% url 'orders:create_order' %}'" type="button">Checkout</button>
                                <button class="btn btn-outline-dark" onclick="window.location.href='{% url 'home' %}'" type="button">Continue shopping</button>
                            </div>
                            <div class="col p-2 text-end">
                                <h4>Total price: $ {{ cart.get_total_price }}</h4>
                            </div>
                        </div>
                    </div>
                        {% endif %}
                    </div>
                </div>

            </section>
        </div>
    </section>
{% endblock %}