cart/urls.py
from django.urls import path
from .views import *


app_name = "cart"

urlpatterns = [
    path("", cart_details, name="cart_details"),
    path("add/<int:product_id>", add_to_cart, name="cart_add"),
    path("remove/<int:product_id>", remove_from_cart, name="cart_remove"),
]

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h3>About my shop</h3>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <style type="text/css">
        body {
            background: linear-gradient(rgba(66, 42, 183, 0.8), rgba(66, 42, 183, 0.8)), url('{% static 'pug.jpg' %}') no-repeat center center fixed;
            background-size: cover;
        }



    </style>
</head>
<body class="d-flex flex-column min-vh-100">
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About us</a></li>
                {% if user.is_superuser %}
                <li><a href="{% url 'admin:index' %}" class="nav-link px-2 text-white">Admin panel</a></li>
                {% endif %}
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" method="get" action="{% url 'search_result' %}">
                <input name="q" type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form>
            {% if user.is_authenticated %}
            {% if not user.is_superuser %}
            <span style="margin-right: 20px">Hello, {{ request.user }} </span>
            <div class="dropdown text-end">
                <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ request.user.profile_user.avatar.url }}" alt="mdo" width="32" height="32"
                         class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                    <li><a class="dropdown-item" href="{% url 'profile_details' request.user.profile_user.slug %}">Profile</a>
                    </li>
                    <li><a class="dropdown-item" href="{% url 'favorites_list' request.user.profile_user.slug %}">Favourites</a></li>
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            <li><a class="dropdown-item" href="{% url 'cart:cart_details' %}">
                                My Cart  <span class="badge bg-danger" style="border-radius: 15px;">{{ total_items }}</span>
                                </a>
                            </li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'cart:cart_details' %}">My Cart</a></li>
                        {% endif %}
                    {% endwith %}
                            <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
                </ul>
            </div>
            {% else %}
            <button type="button" onclick="window.location.href={% url 'logout' %}"
                    class="btn btn-outline-light me-2">Logout
            </button>
            {% endif %}
            {% else %}
            <div class="text-end">
                <button type="button" onclick="window.location.href={% url 'login' %}"
                        class="btn btn-outline-light me-2">Login
                </button>
                <button type="button" onclick="window.location.href={% url 'register' %}" class="btn btn-warning">
                    Sign-up
                </button>
            </div>
            {% endif %}
        </div>
    </div>
</header>
{% block content %}
{% endblock %}
<footer class="bg-dark py-3 mt-auto">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-light">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-light">About</a></li>
    </ul>
    <p class="text-center text-light">© 2024 Fancy-Shop, Inc</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom text-white fw-bold">Product categories:</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
        {% for category in categories %}
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
                 style="background: linear-gradient(rgba(39,37,35, 0.5), rgba(39,37,35,0.5)), url({{ category.image.url }}); background-size: cover;">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ category.name }}</h2>
                    <a href="{% url 'category' category.slug %}" class="stretched-link"></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/pagination.html
<div class="pagination pt-4 pb-4">
    {% if products.has_other_pages %}
        <div class="btn-group" role="group" aria-label="Item pagination">
            {% if products.has_previous %}
                <a href="?page={{ products.previous_page_number }}" class="btn btn-outline-light">&laquo;</a>
            {% endif %}

            {% for page_number in products.paginator.page_range %}
            {% if products.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span><b>{{ page_number }}</b></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-light">
                    {{ page_number }}
                </a>
            {% endif %}
            {% endfor %}

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}" class="btn btn-outline-light">&raquo;</a>
            {% endif %}
        </div>
    {% endif %}
</div>